<?php
/**
 * Diese Klasse enthält die Ländercodes nach Standard ISO 3166.
 * 
 * @author Philipp Kemmeter
 */
class ISO_3166 {
	const AFGHANISTAN = "AF";
	const ALAND_ISLANDS = "AX";
	const ALBANIA = "AL";
	const ALGERIA = "DZ";
	const AMERICAN_SAMOA = "AS";
	const ANDORRA = "AD";
	const ANGOLA = "AO";
	const ANGUILLA = "AI";
	const ANTARCTICA = "AQ";
	const ANTIGUA_AND_BARBUDA = "AG";
	const ARGENTINA = "AR";
	const ARMENIA = "AM";
	const ARUBA = "AW";
	const AUSTRALIA = "AU";
	const AUSTRIA = "AT";
	const AZERBAIJAN = "AZ";
	const BAHAMAS = "BS";
	const BAHRAIN = "BH";
	const BANGLADESH = "BD";
	const BARBADOS = "BB";
	const BELARUS = "BY";
	const BELGIUM = "BE";
	const BELIZE = "BZ";
	const BENIN = "BJ";
	const BERMUDA = "BM";
	const BHUTAN = "BT";
	const BOLIVIA_PLURINATIONAL_STATE_OF = "BO";
	const BOSNIA_AND_HERZEGOVINA = "BA";
	const BOTSWANA = "BW";
	const BOUVET_ISLAND = "BV";
	const BRAZIL = "BR";
	const BRITISH_INDIAN_OCEAN_TERRITORY = "IO";
	const BRUNEI_DARUSSALAM = "BN";
	const BULGARIA = "BG";
	const BURKINA_FASO = "BF";
	const BURUNDI = "BI";
	const CAMBODIA = "KH";
	const CAMEROON = "CM";
	const CANADA = "CA";
	const CAPE_VERDE = "CV";
	const CAYMAN_ISLANDS = "KY";
	const CENTRAL_AFRICAN_REPUBLIC = "CF";
	const CHAD = "TD";
	const CHILE = "CL";
	const CHINA = "CN";
	const CHRISTMAS_ISLAND = "CX";
	const COCOS_KEELING_ISLANDS = "CC";
	const COLOMBIA = "CO";
	const COMOROS = "KM";
	const CONGO = "CG";
	const CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE = "CD";
	const COOK_ISLANDS = "CK";
	const COSTA_RICA = "CR";
	const COTE_D_IVOIRE = "CI";
	const CROATIA = "HR";
	const CUBA = "CU";
	const CYPRUS = "CY";
	const CZECH_REPUBLIC = "CZ";
	const DENMARK = "DK";
	const DJIBOUTI = "DJ";
	const DOMINICA = "DM";
	const DOMINICAN_REPUBLIC = "DO";
	const ECUADOR = "EC";
	const EGYPT = "EG";
	const EL_SALVADOR = "SV";
	const EQUATORIAL_GUINEA = "GQ";
	const ERITREA = "ER";
	const ESTONIA = "EE";
	const ETHIOPIA = "ET";
	const FALKLAND_ISLANDS_MALVINAS = "FK";
	const FAROE_ISLANDS = "FO";
	const FIJI = "FJ";
	const FINLAND = "FI";
	const FRANCE = "FR";
	const FRENCH_GUIANA = "GF";
	const FRENCH_POLYNESIA = "PF";
	const FRENCH_SOUTHERN_TERRITORIES = "TF";
	const GABON = "GA";
	const GAMBIA = "GM";
	const GEORGIA = "GE";
	const GERMANY = "DE";
	const GHANA = "GH";
	const GIBRALTAR = "GI";
	const GREECE = "GR";
	const GREENLAND = "GL";
	const GRENADA = "GD";
	const GUADELOUPE = "GP";
	const GUAM = "GU";
	const GUATEMALA = "GT";
	const GUERNSEY = "GG";
	const GUINEA = "GN";
	const GUINEA_BISSAU = "GW";
	const GUYANA = "GY";
	const HAITI = "HT";
	const HEARD_ISLAND_AND_MCDONALD_ISLANDS = "HM";
	const HOLY_SEE_VATICAN_CITY_STATE = "VA";
	const HONDURAS = "HN";
	const HONG_KONG = "HK";
	const HUNGARY = "HU";
	const ICELAND = "IS";
	const INDIA = "IN";
	const INDONESIA = "ID";
	const IRAN_ISLAMIC_REPUBLIC_OF = "IR";
	const IRAQ = "IQ";
	const IRELAND = "IE";
	const ISLE_OF_MAN = "IM";
	const ISRAEL = "IL";
	const ITALY = "IT";
	const JAMAICA = "JM";
	const JAPAN = "JP";
	const JERSEY = "JE";
	const JORDAN = "JO";
	const KAZAKHSTAN = "KZ";
	const KENYA = "KE";
	const KIRIBATI = "KI";
	const KOREA_DEMOCRATIC_PEOPLE_S_REPUBLIC_OF = "KP";
	const KOREA_REPUBLIC_OF = "KR";
	const KUWAIT = "KW";
	const KYRGYZSTAN = "KG";
	const LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC = "LA";
	const LATVIA = "LV";
	const LEBANON = "LB";
	const LESOTHO = "LS";
	const LIBERIA = "LR";
	const LIBYAN_ARAB_JAMAHIRIYA = "LY";
	const LIECHTENSTEIN = "LI";
	const LITHUANIA = "LT";
	const LUXEMBOURG = "LU";
	const MACAO = "MO";
	const MACEDONIA_THE_FORMER_YUGOSLAV_REPUBLIC_OF = "MK";
	const MADAGASCAR = "MG";
	const MALAWI = "MW";
	const MALAYSIA = "MY";
	const MALDIVES = "MV";
	const MALI = "ML";
	const MALTA = "MT";
	const MARSHALL_ISLANDS = "MH";
	const MARTINIQUE = "MQ";
	const MAURITANIA = "MR";
	const MAURITIUS = "MU";
	const MAYOTTE = "YT";
	const MEXICO = "MX";
	const MICRONESIA_FEDERATED_STATES_OF = "FM";
	const MOLDOVA_REPUBLIC_OF = "MD";
	const MONACO = "MC";
	const MONGOLIA = "MN";
	const MONTENEGRO = "ME";
	const MONTSERRAT = "MS";
	const MOROCCO = "MA";
	const MOZAMBIQUE = "MZ";
	const MYANMAR = "MM";
	const NAMIBIA = "NA";
	const NAURU = "NR";
	const NEPAL = "NP";
	const NETHERLANDS = "NL";
	const NETHERLANDS_ANTILLES = "AN";
	const NEW_CALEDONIA = "NC";
	const NEW_ZEALAND = "NZ";
	const NICARAGUA = "NI";
	const NIGER = "NE";
	const NIGERIA = "NG";
	const NIUE = "NU";
	const NORFOLK_ISLAND = "NF";
	const NORTHERN_MARIANA_ISLANDS = "MP";
	const NORWAY = "NO";
	const OMAN = "OM";
	const PAKISTAN = "PK";
	const PALAU = "PW";
	const PALESTINIAN_TERRITORY_OCCUPIED = "PS";
	const PANAMA = "PA";
	const PAPUA_NEW_GUINEA = "PG";
	const PARAGUAY = "PY";
	const PERU = "PE";
	const PHILIPPINES = "PH";
	const PITCAIRN = "PN";
	const POLAND = "PL";
	const PORTUGAL = "PT";
	const PUERTO_RICO = "PR";
	const QATAR = "QA";
	const R_UNION = "RE";
	const ROMANIA = "RO";
	const RUSSIAN_FEDERATION = "RU";
	const RWANDA = "RW";
	const SAINT_BARTH_LEMY = "BL";
	const SAINT_HELENA = "SH";
	const SAINT_KITTS_AND_NEVIS = "KN";
	const SAINT_LUCIA = "LC";
	const SAINT_MARTIN = "MF";
	const SAINT_PIERRE_AND_MIQUELON = "PM";
	const SAINT_VINCENT_AND_THE_GRENADINES = "VC";
	const SAMOA = "WS";
	const SAN_MARINO = "SM";
	const SAO_TOME_AND_PRINCIPE = "ST";
	const SAUDI_ARABIA = "SA";
	const SENEGAL = "SN";
	const SERBIA = "RS";
	const SEYCHELLES = "SC";
	const SIERRA_LEONE = "SL";
	const SINGAPORE = "SG";
	const SLOVAKIA = "SK";
	const SLOVENIA = "SI";
	const SOLOMON_ISLANDS = "SB";
	const SOMALIA = "SO";
	const SOUTH_AFRICA = "ZA";
	const SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = "GS";
	const SPAIN = "ES";
	const SRI_LANKA = "LK";
	const SUDAN = "SD";
	const SURINAME = "SR";
	const SVALBARD_AND_JAN_MAYEN = "SJ";
	const SWAZILAND = "SZ";
	const SWEDEN = "SE";
	const SWITZERLAND = "CH";
	const SYRIAN_ARAB_REPUBLIC = "SY";
	const TAIWAN_PROVINCE_OF_CHINA = "TW";
	const TAJIKISTAN = "TJ";
	const TANZANIA_UNITED_REPUBLIC_OF = "TZ";
	const THAILAND = "TH";
	const TIMOR_LESTE = "TL";
	const TOGO = "TG";
	const TOKELAU = "TK";
	const TONGA = "TO";
	const TRINIDAD_AND_TOBAGO = "TT";
	const TUNISIA = "TN";
	const TURKEY = "TR";
	const TURKMENISTAN = "TM";
	const TURKS_AND_CAICOS_ISLANDS = "TC";
	const TUVALU = "TV";
	const UGANDA = "UG";
	const UKRAINE = "UA";
	const UNITED_ARAB_EMIRATES = "AE";
	const UNITED_KINGDOM = "GB";
	const UNITED_STATES = "US";
	const UNITED_STATES_MINOR_OUTLYING_ISLANDS = "UM";
	const URUGUAY = "UY";
	const UZBEKISTAN = "UZ";
	const VANUATU = "VU";
	const VENEZUELA_BOLIVARIAN_REPUBLIC_OF = "VE";
	const VIET_NAM = "VN";
	const VIRGIN_ISLANDS_BRITISH = "VG";
	const VIRGIN_ISLANDS_U_S = "VI";
	const WALLIS_AND_FUTUNA = "WF";
	const WESTERN_SAHARA = "EH";
	const YEMEN = "YE";
	const ZAMBIA = "ZM";
	const ZIMBABWE = "ZW";
	
	public static $all_codes = array(
		"AF","AX","AL","DZ","AS","AD","AO","AI","AQ","AG","AR","AM","AW","AU",
		"AT","AZ","BS","BH","BD","BB","BY","BE","BZ","BJ","BM","BT","BO","BA",
		"BW","BV","BR","IO","BN","BG","BF","BI","KH","CM","CA","CV","KY","CF",
		"TD","CL","CN","CX","CC","CO","KM","CG","CD","CK","CR","CI","HR","CU",
		"CY","CZ","DK","DJ","DM","DO","EC","EG","SV","GQ","ER","EE","ET","FK",
		"FO","FJ","FI","FR","GF","PF","TF","GA","GM","GE","DE","GH","GI","GR",
		"GL","GD","GP","GU","GT","GG","GN","GW","GY","HT","HM","VA","HN","HK",
		"HU","IS","IN","ID","IR","IQ","IE","IM","IL","IT","JM","JP","JE","JO",
		"KZ","KE","KI","KP","KR","KW","KG","LA","LV","LB","LS","LR","LY","LI",
		"LT","LU","MO","MK","MG","MW","MY","MV","ML","MT","MH","MQ","MR","MU",
		"YT","MX","FM","MD","MC","MN","ME","MS","MA","MZ","MM","NA","NR","NP",
		"NL","AN","NC","NZ","NI","NE","NG","NU","NF","MP","NO","OM","PK","PW",
		"PS","PA","PG","PY","PE","PH","PN","PL","PT","PR","QA","RE","RO","RU",
		"RW","BL","SH","KN","LC","MF","PM","VC","WS","SM","ST","SA","SN","RS",
		"SC","SL","SG","SK","SI","SB","SO","ZA","GS","ES","LK","SD","SR","SJ",
		"SZ","SE","CH","SY","TW","TJ","TZ","TH","TL","TG","TK","TO","TT","TN",
		"TR","TM","TC","TV","UG","UA","AE","GB","US","UM","UY","UZ","VU","VE",
		"VN","VG","VI","WF","EH","YE","ZM","ZW"
	);
}
?>